behaviors:
  Mk2Agent:
    trainer_type: ppo

    hyperparameters:
      batch_size: 1024
      buffer_size: 81920 # 10 executables x 8 agents x 1024
      learning_rate: 0.0003
      beta: 0.002
      epsilon: 0.4      
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
    max_steps: 5e20
    time_horizon: 16
    summary_freq: 10000
    keep_checkpoints: 35
    checkpoint_interval: 100000
    threaded: true
